-- 不動産物件を保存するテーブル
create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 100),
  rent integer not null check (rent >= 0),
  area text not null check (char_length(trim(area)) between 1 and 100),
  layout text not null check (char_length(trim(layout)) between 1 and 30),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ユーザーごとの一覧取得を高速化する
create index if not exists properties_user_id_created_at_idx
  on public.properties (user_id, created_at desc);

-- 行レベルセキュリティを有効にする
alter table public.properties enable row level security;

-- 自分が登録した物件だけを参照できる
drop policy if exists "自分の物件を参照できる" on public.properties;
create policy "自分の物件を参照できる"
  on public.properties for select
  to authenticated
  using ((select auth.uid()) = user_id);

-- 自分のユーザーIDでのみ物件を登録できる
drop policy if exists "自分の物件を登録できる" on public.properties;
create policy "自分の物件を登録できる"
  on public.properties for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

-- 自分が登録した物件だけを更新できる
drop policy if exists "自分の物件を更新できる" on public.properties;
create policy "自分の物件を更新できる"
  on public.properties for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- 自分が登録した物件だけを削除できる
drop policy if exists "自分の物件を削除できる" on public.properties;
create policy "自分の物件を削除できる"
  on public.properties for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- updated_atを更新時に自動更新する関数
create or replace function public.update_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists properties_update_updated_at on public.properties;
create trigger properties_update_updated_at
  before update on public.properties
  for each row execute function public.update_updated_at();
